language: node_js
node_js: "node"
notifications:
  email: 
    recipients: 
      - dan@mountainhub.com
      - dan@lambdaschool.com
      - dfrehner1@gmail.com
    on_success: always
    on_failure: always